// Code generated from spec/api-parity/v1/manifest.json; DO NOT EDIT.
package actae

// ManifestOperation describes one canonical operation.
type ManifestOperation struct {
	ID             string
	Method         string
	Path           string
	Action         string
	Confirmation   bool
	Idempotency    string
	Transport      string
	Scope          string
	FleetSupported bool
	RequestSchema  string
	ResponseSchema string
}

var ManifestOperations = map[string]ManifestOperation{
	"actae.api.v1.auth.capabilities.get":              {ID: "actae.api.v1.auth.capabilities.get", Method: "GET", Path: "/api/v1/auth/capabilities", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.Capabilities"},
	"actae.api.v1.auth.signup":                        {ID: "actae.api.v1.auth.signup", Method: "POST", Path: "/api/v1/auth/signup", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "public", FleetSupported: false, RequestSchema: "actae.api.v1.SignupRequest", ResponseSchema: "actae.api.v1.AuthTokenResponse"},
	"actae.api.v1.auth.login":                         {ID: "actae.api.v1.auth.login", Method: "POST", Path: "/api/v1/auth/login", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "public", FleetSupported: false, RequestSchema: "actae.api.v1.LoginRequest", ResponseSchema: "actae.api.v1.AuthTokenResponse"},
	"actae.api.v1.auth.api_key_login":                 {ID: "actae.api.v1.auth.api_key_login", Method: "POST", Path: "/api/v1/auth/api-key-login", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "public", FleetSupported: false, RequestSchema: "actae.api.v1.ApiKeyLoginRequest", ResponseSchema: "actae.api.v1.AuthTokenResponse"},
	"actae.api.v1.auth.config.get":                    {ID: "actae.api.v1.auth.config.get", Method: "GET", Path: "/api/v1/auth/config", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "public", FleetSupported: false, RequestSchema: "", ResponseSchema: "actae.api.v1.AuthConfig"},
	"actae.api.v1.auth.me.get":                        {ID: "actae.api.v1.auth.me.get", Method: "GET", Path: "/api/v1/auth/me", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.MeResponse"},
	"actae.api.v1.auth.logout":                        {ID: "actae.api.v1.auth.logout", Method: "POST", Path: "/api/v1/auth/logout", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "public", FleetSupported: false, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.user.preferences.get":               {ID: "actae.api.v1.user.preferences.get", Method: "GET", Path: "/api/v1/user/preferences", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.UserPreferences"},
	"actae.api.v1.user.preferences.put":               {ID: "actae.api.v1.user.preferences.put", Method: "PUT", Path: "/api/v1/user/preferences", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "events:write", FleetSupported: true, RequestSchema: "actae.api.v1.UserPreferencesPut", ResponseSchema: "actae.api.v1.UserPreferences"},
	"actae.api.v1.instance.get":                       {ID: "actae.api.v1.instance.get", Method: "GET", Path: "/api/v1/instance", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.InstanceInfo"},
	"actae.api.v1.events.record":                      {ID: "actae.api.v1.events.record", Method: "POST", Path: "/api/v1/events/record", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "events:write", FleetSupported: true, RequestSchema: "actae.api.v1.PublishEventRequest", ResponseSchema: "actae.api.v1.RecordResponse"},
	"actae.api.v1.events.transition":                  {ID: "actae.api.v1.events.transition", Method: "POST", Path: "/api/v1/events/transition", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "events:write", FleetSupported: true, RequestSchema: "actae.api.v1.TransitionRequest", ResponseSchema: "actae.api.v1.RecordResponse"},
	"actae.api.v1.events.replay":                      {ID: "actae.api.v1.events.replay", Method: "GET", Path: "/api/v1/events/replay/{channel_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.EventList"},
	"actae.api.v1.events.query":                       {ID: "actae.api.v1.events.query", Method: "POST", Path: "/api/v1/events/query", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "actae.api.v1.QueryRequest", ResponseSchema: "actae.api.v1.QueryResponse"},
	"actae.api.v1.events.cursor.get":                  {ID: "actae.api.v1.events.cursor.get", Method: "GET", Path: "/api/v1/events/cursor/{channel_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.CursorResponse"},
	"actae.api.v1.events.verify_chain":                {ID: "actae.api.v1.events.verify_chain", Method: "GET", Path: "/api/v1/events/verify/{channel_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "payloads:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.VerifyChainResponse"},
	"actae.api.v1.events.causal_graph.get":            {ID: "actae.api.v1.events.causal_graph.get", Method: "GET", Path: "/api/v1/events/{event_id}/causal-graph", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "events:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.CausalGraphResponse"},
	"actae.api.v1.channels.list":                      {ID: "actae.api.v1.channels.list", Method: "GET", Path: "/api/v1/channels", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ChannelList"},
	"actae.api.v1.state.save":                         {ID: "actae.api.v1.state.save", Method: "POST", Path: "/api/v1/state/{channel_id}", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "state:write", FleetSupported: true, RequestSchema: "actae.api.v1.SaveStateRequest", ResponseSchema: "actae.api.v1.SaveStateResponse"},
	"actae.api.v1.state.load":                         {ID: "actae.api.v1.state.load", Method: "GET", Path: "/api/v1/state/{channel_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "state:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.StateResponse"},
	"actae.api.v1.state.versions.list":                {ID: "actae.api.v1.state.versions.list", Method: "GET", Path: "/api/v1/state/{channel_id}/versions", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "state:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.StateVersionList"},
	"actae.api.v1.state.version.get":                  {ID: "actae.api.v1.state.version.get", Method: "GET", Path: "/api/v1/state/{channel_id}/version/{version}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "state:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.StateResponse"},
	"actae.api.v1.state.version.delete":               {ID: "actae.api.v1.state.version.delete", Method: "DELETE", Path: "/api/v1/state/{channel_id}/version/{version}", Action: "delete", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "state:delete", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.forks.create":                       {ID: "actae.api.v1.forks.create", Method: "POST", Path: "/api/v1/channels/fork", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "forks:create", FleetSupported: true, RequestSchema: "actae.api.v1.ForkRequest", ResponseSchema: "actae.api.v1.ForkResponse"},
	"actae.api.v1.channels.diff":                      {ID: "actae.api.v1.channels.diff", Method: "GET", Path: "/api/v1/channels/diff", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "state:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.StateDiffResponse"},
	"actae.api.v1.channels.compare":                   {ID: "actae.api.v1.channels.compare", Method: "GET", Path: "/api/v1/channels/compare", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.CompareResponse"},
	"actae.api.v1.channels.outcome.set":               {ID: "actae.api.v1.channels.outcome.set", Method: "PATCH", Path: "/api/v1/channels/{channel_id}/outcome", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "channels:write", FleetSupported: true, RequestSchema: "actae.api.v1.SetOutcomeRequest", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.forks.promote":                      {ID: "actae.api.v1.forks.promote", Method: "POST", Path: "/api/v1/channels/{channel_id}/promote", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "forks:promote", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.PromoteResponse"},
	"actae.api.v1.channels.delete":                    {ID: "actae.api.v1.channels.delete", Method: "DELETE", Path: "/api/v1/channels/{channel_id}", Action: "delete", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "channels:delete", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.channels.metadata.get":              {ID: "actae.api.v1.channels.metadata.get", Method: "GET", Path: "/api/v1/channels/{channel_id}/metadata", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ChannelMetadata"},
	"actae.api.v1.channels.metadata.put":              {ID: "actae.api.v1.channels.metadata.put", Method: "PUT", Path: "/api/v1/channels/{channel_id}/metadata", Action: "write", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "channels:write", FleetSupported: true, RequestSchema: "actae.api.v1.UpdateMetadataRequest", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.channels.steps.latest":              {ID: "actae.api.v1.channels.steps.latest", Method: "GET", Path: "/api/v1/channels/{channel_id}/steps", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.LatestStepResponse"},
	"actae.api.v1.channels.steps.resolve":             {ID: "actae.api.v1.channels.steps.resolve", Method: "GET", Path: "/api/v1/channels/{channel_id}/steps/{step_number}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ResolveStepResponse"},
	"actae.api.v1.channels.forks.list":                {ID: "actae.api.v1.channels.forks.list", Method: "GET", Path: "/api/v1/channels/{channel_id}/forks", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ForkList"},
	"actae.api.v1.channels.fork_tree.get":             {ID: "actae.api.v1.channels.fork_tree.get", Method: "GET", Path: "/api/v1/channels/{channel_id}/fork-tree", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionTree"},
	"actae.api.v1.channels.trail.get":                 {ID: "actae.api.v1.channels.trail.get", Method: "GET", Path: "/api/v1/channels/{channel_id}/trail", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.DecisionTrail"},
	"actae.api.v1.channels.receipt.get":               {ID: "actae.api.v1.channels.receipt.get", Method: "GET", Path: "/api/v1/channels/{channel_id}/receipt", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "channels:read", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ForkReceipt"},
	"actae.api.v1.channels.close":                     {ID: "actae.api.v1.channels.close", Method: "POST", Path: "/api/v1/channels/{channel_id}/close", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "channels:write", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.groups.create":                      {ID: "actae.api.v1.groups.create", Method: "POST", Path: "/api/v1/groups", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CreateGroupRequest", ResponseSchema: "actae.api.v1.GroupInfo"},
	"actae.api.v1.groups.list":                        {ID: "actae.api.v1.groups.list", Method: "GET", Path: "/api/v1/groups", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.GroupList"},
	"actae.api.v1.groups.delete":                      {ID: "actae.api.v1.groups.delete", Method: "DELETE", Path: "/api/v1/groups/{group_id}", Action: "delete", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.groups.join":                        {ID: "actae.api.v1.groups.join", Method: "POST", Path: "/api/v1/groups/{group_id}/join", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.JoinGroupRequest", ResponseSchema: "actae.api.v1.JoinGroupResponse"},
	"actae.api.v1.groups.claim_work":                  {ID: "actae.api.v1.groups.claim_work", Method: "POST", Path: "/api/v1/groups/{group_id}/work", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.ClaimWorkRequest", ResponseSchema: "actae.api.v1.ClaimWorkResponse"},
	"actae.api.v1.groups.ack":                         {ID: "actae.api.v1.groups.ack", Method: "POST", Path: "/api/v1/groups/{group_id}/ack", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.AckRequest", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.groups.heartbeat":                   {ID: "actae.api.v1.groups.heartbeat", Method: "POST", Path: "/api/v1/groups/{group_id}/heartbeat", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.HeartbeatRequest", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.groups.offsets.get":                 {ID: "actae.api.v1.groups.offsets.get", Method: "GET", Path: "/api/v1/groups/{group_id}/offsets", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OffsetsResponse"},
	"actae.api.v1.execution_groups.create":            {ID: "actae.api.v1.execution_groups.create", Method: "POST", Path: "/api/v1/execution-groups", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CreateExecutionGroupRequest", ResponseSchema: "actae.api.v1.ExecutionGroup"},
	"actae.api.v1.execution_groups.list":              {ID: "actae.api.v1.execution_groups.list", Method: "GET", Path: "/api/v1/execution-groups", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupList"},
	"actae.api.v1.execution_groups.members.add":       {ID: "actae.api.v1.execution_groups.members.add", Method: "POST", Path: "/api/v1/execution-groups/{group_id}/members", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.AddExecutionGroupMemberRequest", ResponseSchema: "actae.api.v1.ExecutionGroupMember"},
	"actae.api.v1.execution_groups.members.list":      {ID: "actae.api.v1.execution_groups.members.list", Method: "GET", Path: "/api/v1/execution-groups/{group_id}/members", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupMemberList"},
	"actae.api.v1.execution_groups.members.claim":     {ID: "actae.api.v1.execution_groups.members.claim", Method: "POST", Path: "/api/v1/execution-groups/{group_id}/members/{member_id}/claim", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupMember"},
	"actae.api.v1.execution_groups.members.heartbeat": {ID: "actae.api.v1.execution_groups.members.heartbeat", Method: "POST", Path: "/api/v1/execution-groups/{group_id}/members/{member_id}/heartbeat", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupMember"},
	"actae.api.v1.execution_groups.members.release":   {ID: "actae.api.v1.execution_groups.members.release", Method: "POST", Path: "/api/v1/execution-groups/{group_id}/members/{member_id}/release", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.execution_groups.messages.send":     {ID: "actae.api.v1.execution_groups.messages.send", Method: "POST", Path: "/api/v1/execution-groups/{group_id}/messages", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "actae.api.v1.SendExecutionGroupMessageRequest", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.execution_groups.messages.list":     {ID: "actae.api.v1.execution_groups.messages.list", Method: "GET", Path: "/api/v1/execution-groups/{group_id}/members/{member_id}/messages", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupMessageList"},
	"actae.api.v1.execution_groups.messages.ack":      {ID: "actae.api.v1.execution_groups.messages.ack", Method: "POST", Path: "/api/v1/execution-group-messages/{message_id}/ack", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "execution_groups:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.execution_groups.forks.create":      {ID: "actae.api.v1.execution_groups.forks.create", Method: "POST", Path: "/api/v1/execution-group-forks", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "forks:create", FleetSupported: true, RequestSchema: "actae.api.v1.CreateExecutionGroupForkRequest", ResponseSchema: "actae.api.v1.ExecutionGroupFork"},
	"actae.api.v1.execution_groups.forks.get":         {ID: "actae.api.v1.execution_groups.forks.get", Method: "GET", Path: "/api/v1/execution-group-forks/{fork_group_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "forks:create", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionGroupFork"},
	"actae.api.v1.execution_groups.forks.promote":     {ID: "actae.api.v1.execution_groups.forks.promote", Method: "POST", Path: "/api/v1/execution-group-forks/{fork_group_id}/members/{member_id}/promote", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "forks:promote", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.experiments.create":                 {ID: "actae.api.v1.experiments.create", Method: "POST", Path: "/api/v1/experiments", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "experiments:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CreateExperimentRequest", ResponseSchema: "actae.api.v1.ExperimentGroup"},
	"actae.api.v1.experiments.list":                   {ID: "actae.api.v1.experiments.list", Method: "GET", Path: "/api/v1/experiments", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "experiments:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExperimentGroupList"},
	"actae.api.v1.experiments.get":                    {ID: "actae.api.v1.experiments.get", Method: "GET", Path: "/api/v1/experiments/{group_id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "experiments:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExperimentGroup"},
	"actae.api.v1.experiments.members.add":            {ID: "actae.api.v1.experiments.members.add", Method: "POST", Path: "/api/v1/experiments/{group_id}/members", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "experiments:manage", FleetSupported: true, RequestSchema: "actae.api.v1.AddExperimentMemberRequest", ResponseSchema: "actae.api.v1.ExperimentGroup"},
	"actae.api.v1.experiments.rank":                   {ID: "actae.api.v1.experiments.rank", Method: "GET", Path: "/api/v1/experiments/{group_id}/rank", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "experiments:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.RankResponse"},
	"actae.api.v1.scheduler.wakeups.create":           {ID: "actae.api.v1.scheduler.wakeups.create", Method: "POST", Path: "/api/v1/scheduler/wakeups", Action: "write", Confirmation: false, Idempotency: "operation_id", Transport: "http", Scope: "scheduler:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CreateWakeupRequest", ResponseSchema: "actae.api.v1.WakeupInfo"},
	"actae.api.v1.scheduler.wakeups.list":             {ID: "actae.api.v1.scheduler.wakeups.list", Method: "GET", Path: "/api/v1/scheduler/wakeups", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "scheduler:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.WakeupList"},
	"actae.api.v1.scheduler.wakeups.get":              {ID: "actae.api.v1.scheduler.wakeups.get", Method: "GET", Path: "/api/v1/scheduler/wakeups/{id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "scheduler:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.WakeupInfo"},
	"actae.api.v1.scheduler.wakeups.cancel":           {ID: "actae.api.v1.scheduler.wakeups.cancel", Method: "DELETE", Path: "/api/v1/scheduler/wakeups/{id}", Action: "delete", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "scheduler:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.executions.claim":                   {ID: "actae.api.v1.executions.claim", Method: "POST", Path: "/api/v1/executions/claim", Action: "write", Confirmation: false, Idempotency: "execution_key", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "actae.api.v1.ClaimExecutionRequest", ResponseSchema: "actae.api.v1.Execution"},
	"actae.api.v1.executions.list":                    {ID: "actae.api.v1.executions.list", Method: "GET", Path: "/api/v1/executions", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.ExecutionList"},
	"actae.api.v1.executions.get":                     {ID: "actae.api.v1.executions.get", Method: "GET", Path: "/api/v1/executions/{id}", Action: "read", Confirmation: false, Idempotency: "n/a", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.Execution"},
	"actae.api.v1.executions.delete":                  {ID: "actae.api.v1.executions.delete", Method: "DELETE", Path: "/api/v1/executions/{id}", Action: "delete", Confirmation: false, Idempotency: "none", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "", ResponseSchema: "actae.api.v1.OkResponse"},
	"actae.api.v1.executions.complete":                {ID: "actae.api.v1.executions.complete", Method: "POST", Path: "/api/v1/executions/{id}/complete", Action: "write", Confirmation: false, Idempotency: "execution_key", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CompleteExecutionRequest", ResponseSchema: "actae.api.v1.Execution"},
	"actae.api.v1.executions.fail":                    {ID: "actae.api.v1.executions.fail", Method: "POST", Path: "/api/v1/executions/{id}/fail", Action: "write", Confirmation: false, Idempotency: "execution_key", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "actae.api.v1.FailExecutionRequest", ResponseSchema: "actae.api.v1.Execution"},
	"actae.api.v1.executions.heartbeat":               {ID: "actae.api.v1.executions.heartbeat", Method: "POST", Path: "/api/v1/executions/{id}/heartbeat", Action: "write", Confirmation: false, Idempotency: "execution_key", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "actae.api.v1.HeartbeatExecutionRequest", ResponseSchema: "actae.api.v1.Execution"},
	"actae.api.v1.executions.cancel":                  {ID: "actae.api.v1.executions.cancel", Method: "POST", Path: "/api/v1/executions/{id}/cancel", Action: "write", Confirmation: false, Idempotency: "execution_key", Transport: "http", Scope: "executions:manage", FleetSupported: true, RequestSchema: "actae.api.v1.CancelExecutionRequest", ResponseSchema: "actae.api.v1.Execution"},
}

func ManifestOperationByID(operationID string) (ManifestOperation, bool) {
	op, ok := ManifestOperations[operationID]
	return op, ok
}
